/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HTEaVv16LIo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { signOut } from "next-auth/react";

export function HomePage() {
  return (
    (<main
      className="flex min-h-[100dvh] flex-col items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
      <div className="container mx-auto max-w-3xl space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">solveMyProblem</h1>
          <p className="mt-4 text-gray-500 dark:text-gray-400 md:text-xl">The ultimate problem-solving app.</p>
        </div>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          <Link
            className="flex flex-col items-center justify-center rounded-lg bg-white p-6 shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus-visible:ring-gray-300"
            href="new-submission">
            <PlusIcon className="mb-2 h-8 w-8 text-gray-500 dark:text-gray-400" />
            <span className="text-sm font-medium">Create a new submission</span>
          </Link>
          <Link
            className="flex flex-col items-center justify-center rounded-lg bg-white p-6 shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus-visible:ring-gray-300"
            href="#">
            <ListIcon className="mb-2 h-8 w-8 text-gray-500 dark:text-gray-400" />
            <span className="text-sm font-medium">See all submissions</span>
          </Link>
          <Link
            className="flex flex-col items-center justify-center rounded-lg bg-white p-6 shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus-visible:ring-gray-300"
            href="#">
            <CreditCardIcon className="mb-2 h-8 w-8 text-gray-500 dark:text-gray-400" />
            <span className="text-sm font-medium">Buy credits</span>
          </Link>
          <Link
            className="flex flex-col items-center justify-center rounded-lg bg-white p-6 shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus-visible:ring-gray-300"
            href="#">
            <LogOutIcon className="mb-2 h-8 w-8 text-gray-500 dark:text-gray-400" />
            <span className="text-sm font-medium">Sign out</span>
          </Link>
        </div>
      </div>
    </main>)
  );
}

function CreditCardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>)
  );
}


function ListIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>)
  );
}


function LogOutIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
